### ISSUE TITLE
Listen & Learn - Interaction tabs issue

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#2285] opened 2022-01-18 07:16 UTC
If user clicks anywhere besides the trace...or leaves the step and comes back...Nothing is clickable.
How to edit/add audio? Must trace something..then delete.

<img width="1544" alt="Screen Shot 2022-01-18 at 09 14 09" src="https://user-images.githubusercontent.com/94056434/149888566-64100d7f-e093-47e8-becc-d007e9df016b.png">

**Comment by corinnewo** [comment] 2022-01-26 07:21
@ChaykeeMor I think that this needs to be addressed! This is a bug. How do you suggest to fix this? If you leave the step and come back then you should be able to click a trace?

**Comment by ChaykeeMor** [comment] 2022-01-27 13:03
Well first off, shapes should be clickable at any time. Even if I click off canvas and even if I click away from this step and come back.

As far as the usability, this blank space will have the illustration instruction Gali made with text "Trace and select to add audio or label." and audio/label opens on trace shape correction OR on selection. (I would like 3 visible tabs [trace/audio/label] available to click on but I think Gali does not want that.)

**Comment by corinnewo** [comment] 2022-01-27 15:08
Agreed. Let's get this fixed!

**Comment by corinnewo** [comment] 2022-04-06 13:40
Closing this in favour of #1921, which is a duplicate of the same issue.

**Closed by corinnewo** 2022-04-06 13:40 UTC
Labels: bug, frontend - functionality, Activity: Listen & Learn
