### ISSUE TITLE
One missing letter from the Hebrew series for Ji Alef-Bet converted from Ji Tap

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2740] opened 2022-05-14 16:51 UTC
@MendyBerger THere is one letter missing (בואו נקרא סיפור על האות צ) from the Hebrew series. Please can you check why? I think it might be the same reason that some of the vowel lessons did not appear in the search results when David first imported the games. Pleas can you check? Only showing 21 letters when you search for "בואו נקרא סיפור על האות" . Thanks!

THis was pointed out by some of the teachers in Anat's demo session...

https://jigzi.org/admin/curation/3df635d4-69d3-11ec-8bed-8fc3ed0bbc4d - there is definitely something wrong with this import. Please advise...

**Comment by corinnewo** [comment] 2022-05-16 13:10
See #2744

**Comment by dakom** [comment] 2022-05-23 05:23
Is this a full-on duplicate of https://github.com/ji-devs/ji-cloud/issues/2744 ? i.e. it's fixed now too?

**Comment by corinnewo** [comment] 2022-05-23 15:05
This is fixed in that it is able to play. But the search on Jigzi for "בואו נקרא סיפור על האות צ" does not find this game. When you search for the generic term "בואו נקרא סיפור על האות", there are still only 21 letters showing. This lesson is not in the search results.
@johnnynotsolucky Please can you check why this is not being found in the search on the home page?

**Comment by dakom** [comment] 2022-05-23 15:45
If the game plays and the title / description is there then it's a totally separate Algolia issue

**Comment by johnnynotsolucky** [comment] 2022-05-24 10:59
@corinnewo @RickyLB this may be an issue in the backend.

In Algolia, if I search with "בואו נקרא סיפור על האות", I get 22 results: https://www.algolia.com/apps/RCIA2LNKTS/explorer/browse/release_jig?query=%D7%91%D7%95%D7%90%D7%95%20%D7%A0%D7%A7%D7%A8%D7%90%20%D7%A1%D7%99%D7%A4%D7%95%D7%A8%20%D7%A2%D7%9C%20%D7%94%D7%90%D7%95%D7%AA&refinementList%5Bjig_focus%5D%5B%5D=modules&searchMode=search

If I search with "בואו נקרא סיפור על האות צ" I get 1 exact match: https://www.algolia.com/apps/RCIA2LNKTS/explorer/browse/release_jig?query=%22%D7%91%D7%95%D7%90%D7%95%20%D7%A0%D7%A7%D7%A8%D7%90%20%D7%A1%D7%99%D7%A4%D7%95%D7%A8%20%D7%A2%D7%9C%20%D7%94%D7%90%D7%95%D7%AA%20%D7%A6%22&refinementList%5Bjig_focus%5D%5B%5D=modules&searchMode=search

The ID for the JIG that Corinne linked above matches the ID of the result in Algolia.

**Comment by johnnynotsolucky** [comment] 2022-05-24 11:15
I've updated the privacy level to Public for the JIG and `updated_at` to now so that it should resync with Algolia.

**Comment by johnnynotsolucky** [comment] 2022-05-24 11:18
Algolia has been updated with the changes, and search results are returning the correct amount:

![image](https://user-images.githubusercontent.com/4161106/170022788-cc7b8a28-3e9e-466b-bc1c-573d2b04a452.png)

**Closed by johnnynotsolucky** 2022-05-24 11:18 UTC
Labels: JiTap-Jigzi JIGs
