### ISSUE TITLE
JIG Editing - Add delete notification

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#590] opened 2020-12-28 05:30 UTC
Zplin sketch indicates a notification before deleting activity section. Current Ji Cloud screens do not display this notification. See Loom recording: https://www.loom.com/share/8f0ec073ed3841eaa44e97e48f65c3db 

Please add delete notification/warning before users delete an activity section. 

---

**Zeplin sketch with delete notification:** 

![JIGs_26_DeleteNotification_A_Behavior_Zeplin](https://user-images.githubusercontent.com/74170693/103191686-e6900780-48a3-11eb-956e-129f9af96acd.png)

**Comment by dakom** [comment] 2021-08-13 08:55
Duplicate of https://github.com/ji-devs/ji-cloud/issues/315

**Closed by dakom** 2021-08-13 08:55 UTC
Labels: duplicate
