### ISSUE TITLE
Legacy - tooltip behind the lower bar

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2031] opened 2021-12-16 04:56 UTC
In most sizes, the tooltip was behind the lower bar. In one, it jumped to be displayed above the hotspot rather than below. Can you change the threshold at the bottom so that the tooltip would always show higher, if it is going below the bar?

![image](https://user-images.githubusercontent.com/16290361/146310662-95e37a3f-7356-4e54-a006-92b223edb96e.png)

![image](https://user-images.githubusercontent.com/16290361/146310760-9c10eb8e-56eb-48b3-bb8b-8d0fdc9cd0ae.png)

**Comment by dakom** [comment] 2021-12-18 17:31
Not really... it takes the containing window as the dimensions, it doesn't have knowledge of the jig player controls.

It's not impossible to do a really hacky thing like draw an invisible window, but this won't even work correctly since the jig controls don't scale by the same ratio.

Ultimately, I believe this is a duplicate of https://github.com/ji-devs/ji-cloud/issues/2040 so marking it as such and closing

**Closed by dakom** 2021-12-18 17:31 UTC
Labels: legacy
