### ISSUE TITLE
Finalise the age groups in the database

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1188] opened 2021-07-21 14:31 UTC
In the database, change UNIVERSITY to Pre-K. Final groups are:
Pre-K
Kindergarten
Elementary school
Middle school
High school

Age groups will be shown on the back of the cards.

**Comment by dakom** [comment] 2021-07-27 08:11
Duplicate of #1202

**Closed by dakom** 2021-07-27 08:11 UTC
Labels: duplicate
