### ISSUE TITLE
Cannot get to button--will not scroll

### ISSUE THREAD

**Issue by ChaykeeMor** [ji-devs/ji-cloud#3452] opened 2022-12-13 09:45 UTC
If my screen is too small or even if my browser window is temporarily too small... bottom cuts off and does not permit scrolling and cannot get to the button. On second look, it will scroll if your mouse is over the narrow content area but if my screen is wider and my mouse is off to the right where there is only white space..then it does not work. Wondering if this is a rare case and does not need changing...

https://user-images.githubusercontent.com/94056434/207285833-53be058b-3f22-4942-80d6-e670a3aec59e.mov

**Comment by corinnewo** [comment] 2022-12-13 12:06
We have had a user report the same thing, and Mendy was unable to reproduce it. I think it should be fixed, especially as you would be able to recreate it.

**Comment by MendyBerger** [comment] 2022-12-21 18:18
Was able to reproduce now, thanks

**Comment by MendyBerger** [comment] 2022-12-28 19:27
Resolved

**Closed by MendyBerger** 2022-12-28 19:27 UTC
Labels: bug, login/registration/password
