### ISSUE TITLE
Legacy games with content hidden by progress bar

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2076] opened 2021-12-22 13:59 UTC
Discussed at ideation the idea of having a solid progress bar below the content, and it was absolutely rejected!

Shuli insists that the legacy games are a different ratio already to the 16:9 games, so rather make them slightly smaller and place them above the bar.

Player for 16:9 games remains unchanged, but must implement the grid as requested in the creator area when placing stickers. (#1383)

![image](https://user-images.githubusercontent.com/16290361/147103944-d6dbc826-9f9e-482e-b07b-77bbf6a570f9.png)

**Comment by MendyBerger** [comment] 2021-12-23 12:56
@corinnewo mind sharing the rationale behind this decision?

**Comment by dakom** [comment] 2021-12-23 14:57
Is this not an exact duplicate of https://github.com/ji-devs/ji-cloud/issues/2040 ?

**Comment by MendyBerger** [comment] 2021-12-27 13:19
It is, closing

**Closed by MendyBerger** 2021-12-27 13:19 UTC
Labels: high, legacy
