### ISSUE TITLE
JIG Editing - Add advanced feature menu for "Duplicate" 

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#582] opened 2020-12-25 05:32 UTC
Zeplin sketch indicates that there should be a special menu after duplicating an activity/module. Current Ji Cloud screen does not include this advanced feature. See loom recording: https://www.loom.com/share/bceabdc303ae4a93b5c625e6b8251647

Please add advanced features menu after users duplicate activity. 

---

**Zeplin Sketch with advanced features menu:** 

![JIGs_14_AdvacnedOptionMenu_A_Print_Zeplin](https://user-images.githubusercontent.com/74170693/103121084-8ea99480-4648-11eb-92d5-e23a396d25e4.png)

**Comment by dakom** [comment] 2021-08-13 08:54
duplicate of https://github.com/ji-devs/ji-cloud/issues/1303

**Closed by dakom** 2021-08-13 08:54 UTC
Labels: med, duplicate
