### ISSUE TITLE
Sign Up One (Storybook) - Correct display to test controls

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#648] opened 2021-01-14 05:41 UTC
Error message dominates display and prevents manual QA testing.

Please resolve error message for manual QA testing.

---

**Storybook screenshot of controls:**

![Registration_58_A_SignUpOne_Controls_SB](https://user-images.githubusercontent.com/74170693/104549628-3d664280-5601-11eb-9a2f-51b82347bc4a.png)

**Comment by dani-ji** [comment] 2021-01-14 05:44
Duplicate of #640

**Closed by dani-ji** 2021-01-14 05:44 UTC
