### ISSUE TITLE
QA Publish (Publish Full Two) - Add "Embed this JIG" as "Select Share Option" on dropdown list 

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#694] opened 2021-01-18 06:31 UTC
[Zeplen Sketches](https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5fb6da211ca70f44c6fe7c28) include "Embed this JIG" as an option on dropdown list for "Select Share Option" as well as the associated [flow](https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5fb6da2318090f84a3079135) for this interaction. Current [Storybook screen](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-two) is missing this option on the dropdown list. 

Please add "Embed this JIG" + associated flow as an option for "Select Share Option".

---

**Zeplin Sketch (with "Embed this JIG"):**

![Publish_24_A_PublishFullTwo_DropDownOptions_Zeplin](https://user-images.githubusercontent.com/74170693/104879820-92b99100-592c-11eb-97a9-f59f93e92bec.png)

---

**Zeplin Sketch (with "Embed this JIG" flow):** 

![Publish_24_C_PublishFullTwo_DropDownOptionsEmbed_Zeplin](https://user-images.githubusercontent.com/74170693/104879822-93522780-592c-11eb-897b-40049f1b91b0.png)

---

**Storybook Screen (missing "Embed this JIG"):**

![Publish_24_B_PublishFullTwo_DropDownOptions_SB](https://user-images.githubusercontent.com/74170693/104879821-92b99100-592c-11eb-8a28-ba451961a9da.png)

**Comment by NaomiLea** [comment] 2021-01-25 18:04
Waiting to merge.

**Comment by dakom** [comment] 2021-08-13 09:51
duplicate of https://github.com/ji-devs/ji-cloud/issues/1321

**Closed by dakom** 2021-08-13 09:51 UTC
Labels: frontend - visual, duplicate
