### ISSUE TITLE
QA Publish (Publish Full One) - Add flow for "Add Curriculum"/"Add Lesson Plan"

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#689] opened 2021-01-18 05:42 UTC
[Zeplin sketches](https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5fbbc2162742576ab0854dba) include flow for "Add Curriculum"/"Add Lesson Plan". Current [Storybook screens](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-one) do not include this flow.

Please add missing flow for "Add Curriculum"/"Add Lesson Plan".

---

**Zeplin sketches of "Add Curriculum"/"Add Lesson Plan" flow:**

![Publish_17_A_PublishFullOne_AdditionalResourcesFlow1_Zeplin](https://user-images.githubusercontent.com/74170693/104876471-c04f0c00-5925-11eb-86a7-0ade4bc1aa2b.png)

![Publish_17_B_PublishFullOne_AdditionalResourcesFlow2_Zeplin](https://user-images.githubusercontent.com/74170693/104876472-c0e7a280-5925-11eb-91ba-ab9e758f8fb6.png)

![Publish_17_C_PublishFullOne_AdditionalResourcesFlow3_Zeplin](https://user-images.githubusercontent.com/74170693/104876473-c0e7a280-5925-11eb-9f21-bb3f4cb16e0f.png)

![Publish_17_D_PublishFullOne_AdditionalResourcesFlow4_Zeplin](https://user-images.githubusercontent.com/74170693/104876474-c0e7a280-5925-11eb-95c6-bcebba6d33ce.png)

![Publish_17_E_PublishFullOne_AdditionalResourcesFlow5_Zeplin](https://user-images.githubusercontent.com/74170693/104876475-c0e7a280-5925-11eb-8deb-4798c0ed2d75.png)

![Publish_17_F_PublishFullOne_AdditionalResourcesFlow6_Zeplin](https://user-images.githubusercontent.com/74170693/104876476-c1803900-5925-11eb-9a56-8e892a49a7c5.png)

![Publish_17_G_PublishFullOne_AdditionalResourcesFlow7_Zeplin](https://user-images.githubusercontent.com/74170693/104876477-c1803900-5925-11eb-8035-f1b460085f32.png)

![Publish_17_H_PublishFullOne_AdditionalResourcesFlow8_Zeplin](https://user-images.githubusercontent.com/74170693/104876478-c1803900-5925-11eb-8155-d3502a549f34.png)

**Comment by dakom** [comment] 2021-08-13 09:08
duplicate of https://github.com/ji-devs/ji-cloud/issues/1315

**Closed by dakom** 2021-08-13 09:08 UTC
Labels: frontend - visual, duplicate
