### ISSUE TITLE
At module end, the continue is not going anywhere

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1425] opened 2021-08-23 11:28 UTC
I have pressed DONE in the Preview stage of a module, then get 'What do you want to do now?" I click CONTINUE and nothing happens.
Should open up the JIG panel with the current module highlighted, and ready for working on the next module.

![image](https://user-images.githubusercontent.com/16290361/130439838-683d17d4-efa0-4ce7-95ca-44acf3232adb.png)

**Comment by dakom** [comment] 2021-08-23 13:04
Duplicate of https://github.com/ji-devs/ji-cloud/issues/1419

**Closed by dakom** 2021-08-23 13:04 UTC
Labels: high, needs triage, duplicate
