### ISSUE TITLE
Login Sign Up Two (Storybook) - Reconcile Location Fields 

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#623] opened 2021-01-08 03:48 UTC
Storybook screen matches Zeplin sketch, however neither of them match the previous Ji Cloud screens for Location fields. I'm flagging this since the edit may have been intentional, but I'm not sure if one format is preferred over the other. 

Please keep an eye on "Location" fields, and reconcile as necessary.

---

**Previous Ji Cloud Screen with Location fields:**

![Registration_44_A_SignUpOne_Location_Ji](https://user-images.githubusercontent.com/74170693/103972031-1bb91700-513a-11eb-9024-32b937d3c8b4.png)

---

**Storybook Screen of Location fields:**

![Registration_44_B_SignUpOne_Location_SB](https://user-images.githubusercontent.com/74170693/103972033-1bb91700-513a-11eb-9b00-f3af446608b9.png)

---

**Zeplin Screen of Location fields:**

![Registration_44_C_SignUpOne_Location_Zeplin](https://user-images.githubusercontent.com/74170693/103972034-1bb91700-513a-11eb-9a10-daaf063ddd34.png)

**Comment by dani-ji** [comment] 2021-01-08 04:19
@corinnewo please advise if this is an intentional switch

**Comment by dani-ji** [comment] 2021-01-18 16:30
Duplicate of #701 @dakom tagging you as you brought this up

**Comment by esteels** [comment] 2021-02-11 06:37
@corinnewo Reopening issue to determine how users will input their location.

@dakom is there an implementation reason we used Google locator in the earlier live version (https://jicloud.org/user/register) as opposed to the Country, State, City dropdown menus from Zeplin? Are the Country, State, City dropdown menus a viable option? 

If Country, State, City dropdown menus are a viable option, @corinnewo what do you prefer?

A. Country, State, City dropdown menus 
B. Google locator

@dani-ji tagging you to keep track of this too.

**Comment by dakom** [comment] 2021-02-11 07:02
The live version is correct, Zeplin is outdated.

Long story short, location is very complicated for a global audience, and the Google api has become a standard solution of compromises people are familiar with.

We will eventually, maybe, write a backend utility to parse the data, but for now we use google to steer them towards a city, state, etc. but don't stop them from setting a county, island, street or whatever.

This decision was approved by Chana

**Comment by dani-ji** [comment] 2021-02-12 11:25
Discussed again at the sprint meeting 2/11 and confirmed with Chana/Corinne that we will use a single location field that just needs to be renamed to city

**Closed by dani-ji** 2021-02-12 11:25 UTC
