### ISSUE TITLE
There is a pause - Perhaps we need a loader animation?  

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1800] opened 2021-11-03 15:09 UTC
There is a pause of a few seconds from dragging an activity to the JIG panel - until the activity screen is open.
Also when I click on the preview step.
If its something that will keep happening I suggest to add a loader animation

**Comment by corinnewo** [comment] 2021-11-05 08:54
Duplicate of #1824

**Closed by corinnewo** 2021-11-05 08:54 UTC
