### ISSUE TITLE
QA Publish (Publish Full One) - Add pop up for JIG public vs private toggle

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#688] opened 2021-01-18 05:38 UTC
[Zeplin sketches](https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5fb2adf058d5bf6662160975) include a pop up notification when users toggle settings to make JIG private. Current [Storybook screen](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-one) is missing this notification.

Please ad pop up for JIG public vs private toggle.
(ie make public vs private a state; would this be reflected in controls?) 

---

**Zeplin Sketch (with pop up notification):**

![Publish_16_A_PublishFullOne_SharePopUp_Zeplin](https://user-images.githubusercontent.com/74170693/104876187-2a1ae600-5925-11eb-96b7-e98b38fb3b22.png)

---

**Storybook screen (without notification):**

![Publish_16_B_PublishFullOne_SharePopUp_SB](https://user-images.githubusercontent.com/74170693/104876189-2ab37c80-5925-11eb-8023-c008f39e3a06.png)

**Comment by NaomiLea** [comment] 2021-01-25 18:03
Waiting for merge then can be checked.

**Comment by chayaml** [comment] 2021-02-03 18:03
Storybook Screen still missing pop up notification when users toggle screen to make JIG private. 

Please add pop up for JIG private vs. pop up toggle.


![Screen Shot 2021-02-03 at 9 22 41 AM](https://user-images.githubusercontent.com/78186896/106789400-36d75380-6620-11eb-9b26-df321f6f5c9e.png)

**Comment by NaomiLea** [comment] 2021-02-11 11:07
Fixed

**Comment by dakom** [comment] 2021-08-13 09:49
duplicate of https://github.com/ji-devs/ji-cloud/issues/1320

**Closed by dakom** 2021-08-13 09:49 UTC
Labels: frontend - visual, duplicate
