### ISSUE TITLE
QA Publish (Publish Full One) - ensure # of categories is displayable in dropdown

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#686] opened 2021-01-18 05:27 UTC
[Zeplin sketches](https://app.zeplin.io/project/5f10b1dc713f249d469be791/screen/5fb28f7ee045c169dccedc78) indicate that "Categories" dropdown menu should ultimately display number of categories. Current [Storybook screen](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-one) does not reflect this in its design. Issue #631 noted that dropdown menus are not ready for QA testing, but logging this here for future reference. 

Please ensure that the number of categories will be displayable in dropdown menu.

---

**Zeplin Sketch (with number of categories):**

![Publish_13_A_PublishFullOne_Categories_Zeplin](https://user-images.githubusercontent.com/74170693/104875655-cd6afb80-5923-11eb-9266-e55b4c8ff1ea.png)

---

**Storybook Screen (with placeholder):**

![Publish_13_B_PublishFullOne_Categories_SB](https://user-images.githubusercontent.com/74170693/104875657-ce039200-5923-11eb-9e55-47bd9ec7c944.png)

**Comment by NaomiLea** [comment] 2021-01-18 10:07
Fixed

**Comment by NaomiLea** [comment] 2021-01-18 10:08
Sorry, this one isnt fixed yet.

**Comment by NaomiLea** [comment] 2021-01-20 18:45
This one is fixed on the CSS side. Displaying the numbers of chosen cateogories is on the implementation side.

**Comment by dakom** [comment] 2021-08-13 09:55
duplicate of https://github.com/ji-devs/ji-cloud/issues/1322

**Closed by dakom** 2021-08-13 09:55 UTC
Labels: frontend - visual, duplicate
