### ISSUE TITLE
Jiggling text - put back ability to 'Don't show again'

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2221] opened 2022-01-10 10:15 UTC
At the moment, the dialog appears on each screen. We used to have 'Don't show me again' option, which was really useful. Please put it back! 

- If I click 'Don't show again', then the dialog does not appear again automatically. 
- If no dialog but I click the Jiggling, then the dialog shoes (like help on demand)

![image](https://user-images.githubusercontent.com/16290361/148749375-3dcca147-baf5-452f-ba62-f79ee1bc47d9.png)

**Comment by MendyBerger** [comment] 2022-01-10 15:06
Duplicate of #2103

**Closed by MendyBerger** 2022-01-10 15:06 UTC
