### ISSUE TITLE
Resources - tried to add PDF of 22MB, got message that 30MB is the limit and then it crashed

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2185] opened 2022-01-06 08:43 UTC
I tried to add a resource of 22 MB, got feedback that it was more than 30 MB, and then I got the oops screen!
What is the real limit here? If it is not 30, then we need to change the message.

![image](https://user-images.githubusercontent.com/16290361/148354684-9efaf437-39d6-4ddc-8f28-752cedda8af2.png)

![image](https://user-images.githubusercontent.com/16290361/148355652-1ee155bc-b4d5-4d00-82d1-0301d24b54ed.png)

**Comment by MendyBerger** [comment] 2022-01-06 20:52
@mastapegs assigning to you but I'm not sure what the issue is, mind looking into this?

**Comment by corinnewo** [comment] 2022-03-18 09:12
@mastapegs @MendyBerger I am trying to upload PDF files of flashcards and educator files, and even though they are 20MB, I am still getting this error message that it is over 30MB and not able to upload. Why is this still happening? 
![image](https://user-images.githubusercontent.com/16290361/158974213-12feebcf-614e-4165-9a12-b0ab9f7f7733.png)

**Comment by johnnynotsolucky** [comment] 2022-06-10 07:05
@corinnewo the filesize limit is working correctly, the error message is incorrect. The limit on PDFs is 10mb, not 30mb. 

Would it be reasonable to expect PDFs bigger than 10mb?

**Comment by corinnewo** [comment] 2022-06-10 07:28
If it is greater than 10MB, then I have been putting in a link to dropbox. I think it is reasonable to limit it to 10MB. But then, please change the message!

**Closed** 2022-10-03 17:11 UTC
Labels: Resources
