### ISSUE TITLE
Menu does not have the touch areas (not in Jigzi, but in Ji Tap they are there)

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#3431] opened 2022-12-12 10:43 UTC
https://jigzi.org/asset/play/jig/34076556-b91b-11ec-916d-9b10376872e0?direction=ltr&display_score=false&track_assessments=false&drag_assist=false&is_student=false&draft_or_live=live

Screen  11 working, but 15, 23, 25 - no touch areas defined.

**Comment by dakom** [comment] 2022-12-12 17:40
Probably a duplicate of https://github.com/ji-devs/ji-cloud/issues/3430#issuecomment-1346271200

This game existed previously too

In this case it's even clear to see at the data level - it tries to load photo24.json which does not even exist in the new updated version

**Comment by dakom** [comment] 2022-12-23 13:27
Fixed (I only tested slide 15 though)

**Closed** 2022-12-24 19:27 UTC
Labels: legacy
