### ISSUE TITLE
Affiliations - write a utility to 'check' the boxes of all the other affiliations if 'show me everything' checked

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1187] opened 2021-07-21 13:46 UTC
In order for the filters to work, we need to eliminate the option of 'Show me everything'. 
But before eliminating, we need to make sure that if 'Show me everything' was checked, then all the the affiliations should be checked. Need a utility to do this.

Then, we can delete (or simply hide from admin interface, if deleting is not an option) the admin option to 'Show me everything'. Instead, when an image is uploaded, automatically, all the affiliations are checked, and tagger would then need to **opt out** of options where this image would not be suitable.

We need this utility for **Affiliations** and **Ages** (if all ages checked, then check all the age groups)

**Comment by dakom** [comment] 2021-07-27 08:04
Duplicate of #1203 and #1202

**Closed by dakom** 2021-07-27 08:04 UTC
Labels: duplicate
