### ISSUE TITLE
Labeling Images - Add running header/banner + image search field

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#775] opened 2021-01-31 19:40 UTC
Zeplin sketches include running header/banner + image search field across Labeling Images flow. Current SB flow does not include this header/banner + image search field

Please add running header/banner + image search field for Labeling Images.

---

**Zeplin Sketches (with running header/banner + image search field):**

![Labeling2_002_A_Confirmation_MissingHeader_Zeplin](https://user-images.githubusercontent.com/74170693/106395797-321d6000-63d2-11eb-9448-021406c2f944.png)

**SB Screen (missing running header/banner + image search field):**

![Labeling2_002_B_Confirmation_MissingHeader_SB](https://user-images.githubusercontent.com/74170693/106395799-32b5f680-63d2-11eb-852d-bccf1b0116d8.png)

**Comment by dakom** [comment] 2021-08-13 09:34
duplicate of #1312

**Closed by dakom** 2021-08-13 09:34 UTC
Labels: frontend - visual, duplicate
