### ISSUE TITLE
QA Publish (Publish Full One) - Add default text [placeholder?] for JIGs Name

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#681] opened 2021-01-18 05:03 UTC
[Zeplin sketches](https://app.zeplin.io/project/5fd249c98c6a325399642201/screen/5fe1a1570c56693dee495b9c) include default/grey text for each of the fields of Publish Full One screen. Current [Storybook screen](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-one) is missing default text (even placeholder) in "JIG's name" field. 

Please add default/grey text for the "JIG's name" field.

---

**Zeplin Sketch (with JIG's name field filled out):**

![Publish_04_A_PublishFullOne_EmptyFieldsText_Zeplin](https://user-images.githubusercontent.com/74170693/104874192-4ec08f00-5920-11eb-93bf-08cdcabdd9d5.png)

---

**Storybook Screen (with empty JIG's name field):**

![Publish_04_B_PublishFullOne_EmptyFieldsText_SB](https://user-images.githubusercontent.com/74170693/104874193-4ec08f00-5920-11eb-85be-34e2da384d65.png)

**Comment by NaomiLea** [comment] 2021-01-20 12:20
This is ready to be checked

**Comment by esteels** [comment] 2021-01-22 06:10
@NaomiLea not previewing correctly for me on SB [Publish Full One](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-one)

---

![Publish_04_C_PublishFullOne_EmptyFieldsText_SB_Round2](https://user-images.githubusercontent.com/74170693/105453686-8eec7e00-5c4e-11eb-9e52-06ca7aa4bfb4.png)

**Comment by chayaml** [comment] 2021-02-03 14:33
Default text/ placeholder still missing in "JIG's name" field in [Storybook](https://storybook.sandbox.jicloud.org/?path=/story/entry-jig-publish-pages--publish-full-one).

 Please Add default/ grey text for the "JIG's name" field.

![Screen Shot 2021-02-03 at 9 22 41 AM](https://user-images.githubusercontent.com/78186896/106761422-cd951780-6602-11eb-8935-d6d717c51ef6.png)

**Comment by NaomiLea** [comment] 2021-02-11 14:50
Fixed

**Comment by dakom** [comment] 2021-08-13 09:48
duplicate of https://github.com/ji-devs/ji-cloud/issues/1319

**Closed by dakom** 2021-08-13 09:48 UTC
Labels: frontend - visual, duplicate
