### ISSUE TITLE
JIG panel - theme settings are not saving

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1634] opened 2021-10-12 14:56 UTC
1. I set the theme in the panel to 'surreal'.
2. Reloaded the page
3. Theme in JIG settings is now 'blank' again
![image](https://user-images.githubusercontent.com/16290361/136979778-8c9e4b0e-b730-4597-b3b4-2c96d91ce9cb.png)

Should have retained the JIG settings and therefore the theme that had been chosen.

**Comment by MendyBerger** [comment] 2021-11-05 16:06
Can't recreate, mind checking if still happening?

**Comment by MendyBerger** [comment] 2021-11-08 14:05
Duplicate of #1739

**Closed by MendyBerger** 2021-11-08 14:05 UTC
Labels: frontend - functionality, med
