### ISSUE TITLE
Flashcard play is still not correct when pair shown on screen side-by-side

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1535] opened 2021-09-10 08:16 UTC
Think of the flashcard as front has column 1, back has corresponding column 2. When you click the covered card, it should show the partner of the uncovered card. Eg. side 1= 'Ear' and side 2=picture of ear.

If you have words and pictures, then the uncovered card should be the corresponding word to the picture on the uncovered card.

At the moment, I am getting 2 words, 2 pictures... Should display 'Ear', and the uncovered card would be the picture of the ear, not 'Ear'.

Should never get deck finished. It should continue to randomly show flashcards until user continues with arrow to go to next module. PERHAPS WE SHOULD HAVE A SETTING FOR EITHER INFINITE ROUNDS OR SET NUMBER OF ROUNDS? @GaliShapira - what do you suggest here? Also, Gali - what to show when end of set?

I see this mainly as a classroom activity with teachers showing a card and the kids shout out the answer.

**Comment by dakom** [comment] 2021-09-10 09:29
duplicate of #1533 and #1534

**Closed by dakom** 2021-09-10 09:29 UTC
Labels: duplicate
