### ISSUE TITLE
QA Publish (Publish Full One) - add hover state for "Add Curriculum" 

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#683] opened 2021-01-18 05:11 UTC
Zeplin sketches indicate idle/hover/uploaded states for the "Add Curriculum" elements beneath the "Additional resources (Optional)" header. Current Storybook screen does not reflect hover state.

Please add hover state for mouse over "Add Curriculum".

---

**Zeplin Sketches (with three states):**

![Publish_06_A_PublishFullOne_HoverOverAdditionalResources_Zeplin](https://user-images.githubusercontent.com/74170693/104874680-7cf29e80-5921-11eb-963f-fc73742ad1a4.png)

---

**Storybook screen (no hover state):**

![Publish_06_B_PublishFullOne_HoverOverAdditionalResources_SB](https://user-images.githubusercontent.com/74170693/104874681-7d8b3500-5921-11eb-9838-5de05ea5927c.png)

**Comment by dakom** [comment] 2021-08-13 09:08
duplicate of https://github.com/ji-devs/ji-cloud/issues/1315

**Closed by dakom** 2021-08-13 09:08 UTC
Labels: frontend - visual, duplicate
