### ISSUE TITLE
Publish page - Title to the thumbnail

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#1530] opened 2021-09-09 14:47 UTC
Hi @corinnewo
I added a title to the thumbnail, so its clear when empty.
https://zpl.io/bJoQWOx

<img width="410" alt="Screen Shot 2021-09-13 at 13 40 15" src="https://user-images.githubusercontent.com/88834002/133073895-afa89962-63e4-4d86-b2cb-98d54dbb476a.png">
<img width="443" alt="Screen Shot 2021-09-13 at 13 40 06" src="https://user-images.githubusercontent.com/88834002/133073911-ba2ab606-98b4-4f29-9483-cbd7237887aa.png">

**Comment by MendyBerger** [comment] 2021-09-30 10:38
Duplicate of #1569

**Closed by MendyBerger** 2021-09-30 10:38 UTC
Labels: frontend - visual, frontend - functionality
