### ISSUE TITLE
QA Publish (Publish Full One) - Add responsive delete icon/button

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#680] opened 2021-01-18 04:58 UTC
[Zeplin sketches](https://app.zeplin.io/project/5fd249c98c6a325399642201/screen/5fe1a4bbb02ce93c385bd68b) indicate a delete button // bin icon with hover over states after each row of "Additional resources (Optional). Current [Storybook screen](https://storybook.sandbox.jicloud.org/?path=/story/full-pages-publish--publish-full-one) is missing the responsive icon.

Please add responsive delete icon/button.

---

**Zeplin Sketch (icon + hover over response):**

![Publish_03_A_PublishFullOne_RemoveIconButton_Zeplin](https://user-images.githubusercontent.com/74170693/104873939-b4604b80-591f-11eb-8bba-3632e91fea49.png)

---

**Storybook screen (missing icon):**

![Publish_03_B_PublishFullOne_RemoveIconButton_SB](https://user-images.githubusercontent.com/74170693/104873941-b4f8e200-591f-11eb-8e7f-1adcc7760cd3.png)

**Comment by NaomiLea** [comment] 2021-01-27 15:41
@dakom can you assist with hover 
should be in this file elements/src/core/titles/variants/title-w-icon.ts

**Comment by dakom** [comment] 2021-08-13 09:07
duplicate of https://github.com/ji-devs/ji-cloud/issues/1315

**Closed by dakom** 2021-08-13 09:07 UTC
Labels: frontend - visual, duplicate
