### ISSUE TITLE
iPad sizing on customer's iPad

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2613] opened 2022-03-31 10:21 UTC
A user reported that their student is seeing the player really small on her iPad. See image:
![IMG_0634 (1)](https://user-images.githubusercontent.com/16290361/161033516-7dff67e1-6cbb-4c87-9904-594c6c8a20aa.PNG)

She sent this in response to spec request:
It’s a 6th generation iPad running on iOS 14.5.1. It’s doing the same thing on both Google Chrome and Safari, even when I reload the page or start the search over in a new tab. Not sure if there’s a setting or something I should check.

**Comment by corinnewo** [comment] 2022-03-31 12:40
Leaving this open until I hear back from user regarding zooming, or using landscape.

**Comment by corinnewo** [comment] 2022-04-05 09:30
The customer has sent a video of Jigzi on her ipad. Her ipad is  a 6th generation iPad running on iOS 14.5.1. It’s doing the same thing on both Google Chrome and Safari.

Please can you look into this?

https://user-images.githubusercontent.com/16290361/161723834-0e23ead3-98bb-4c34-955f-8555d4564958.MP4

.

**Comment by MendyBerger** [comment] 2022-07-29 16:52
Closing as duplicate of #2904

**Closed by MendyBerger** 2022-07-29 16:52 UTC
Labels: bug, frontend - visual, Responsive issue, iPad
