### ISSUE TITLE
Creator - Sticker kebab menu - should always open within the screen.

### ISSUE THREAD

**Issue by GaliShapira** [ji-devs/ji-cloud#3656] opened 2023-02-09 15:20 UTC
At the moment if the sticker is placed near the edge or rotated, the menu is cut out.

<img width="1440" alt="Screen Shot 2023-02-08 at 12 08 47" src="https://user-images.githubusercontent.com/88834002/217854940-3e49b3cf-0969-4cf0-9e50-21e81389c36c.png">

<img width="1440" alt="Screen Shot 2023-02-08 at 12 09 38" src="https://user-images.githubusercontent.com/88834002/217854267-58e9b7d7-3a93-4832-a3ed-d189881acf14.png">

**Comment by corinnewo** [comment] 2023-10-16 12:45
Duplicate of #3601

**Closed by corinnewo** 2023-10-16 12:45 UTC
Labels: frontend - visual

**Comment by corinnewo** [comment] 2023-11-21 12:40
closing in favor of https://github.com/ji-devs/ji-cloud/issues/4095
