### ISSUE TITLE
JIG edit Move up/down works incorrectly when no cover is present

### ISSUE THREAD

**Issue by johnnynotsolucky** [ji-devs/ji-cloud#3336] opened 2022-11-07 06:27 UTC
**Describe the bug**
When editing a JIG, if the JIG has no cover set, the "Move up"/"Move down" actions are offset by +1 for the position index sent to the server. The frontend renders the position correctly until the JIG is reloaded, at which point the offset is visible.

https://user-images.githubusercontent.com/4161106/200240123-95000474-8fbe-4fd0-b746-dd7db645fae6.mov

**Comment by corinnewo** [comment] 2022-11-07 06:47
I thought that his had been resolved! Mendy and Ricky were working on it.  @MendyBerger, what is happening here again?

**Comment by MendyBerger** [comment] 2022-11-10 15:49
Duplicate of #3216

**Closed by MendyBerger** 2022-11-10 15:49 UTC
Labels: bug
