### ISSUE TITLE
Player - report button - where does the email go? Is there an email?

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#1440] opened 2021-08-24 14:13 UTC
The report button looks like it is working.
Where does the email go? 

![image](https://user-images.githubusercontent.com/16290361/130632335-9686b999-1a66-44ed-abb5-49eea9fa96b2.png)

**Comment by MendyBerger** [comment] 2021-08-24 15:43
This is not yet implemented

Closing as duplicate of #1263

**Closed by MendyBerger** 2021-08-24 15:43 UTC
Labels: frontend - visual
