### ISSUE TITLE
Categories - Missing header/banner with user information

### ISSUE THREAD

**Issue by esteels** [ji-devs/ji-cloud#475] opened 2020-12-02 05:25 UTC
Please add header/banner with user information (profile picture, name, etc.)

Zeplin sketch for reference: https://www.loom.com/i/09999df8e52448e6971383305dd01444 (see top right)

Current Ji Cloud Categories page: https://www.loom.com/i/64ec804c3c0c4d42a2236643e14d2af1 (missing header/banner)

**Comment by dakom** [comment] 2021-08-13 08:28
Duplicate of #1312

**Closed by dakom** 2021-08-13 08:28 UTC
Labels: frontend - visual, med, duplicate
