### ISSUE TITLE
Legacy - the player bar along the bottom is covering a lot of content

### ISSUE THREAD

**Issue by corinnewo** [ji-devs/ji-cloud#2040] opened 2021-12-17 12:12 UTC
Is there some way to make the legacy games a little smaller and place them above the bar? In Jigzy, creators will be able to see that the content is going to be covered, but in Ji Tap legacy, can't redo. Any ideas? 

![image](https://user-images.githubusercontent.com/16290361/146543097-a54845b8-694b-44b0-a4f3-d70ff4332b5e.png)

**Comment by corinnewo** [comment] 2021-12-17 12:18
ESPECIALLY bad here, where the words are hidden.

![image](https://user-images.githubusercontent.com/16290361/146543542-8e804696-0d00-4ba2-aaeb-efe888690e77.png)

@GaliShapira please look at this - perhaps we need the player bar to be a little narrower?

**Comment by dakom** [comment] 2021-12-17 12:56
This isn't legacy-player specific, it's the jig player as a whole.

Personally I like the typical video player approach where the controller bar is completely outside the content, but it's up to @GaliShapira 

In any case, re-assigning since there isn't anything for me to do on this

**Comment by dakom** [comment] 2021-12-21 17:45
As a non-legacy example, adding a tapping board with a hotspot at the bottom is problematic:
![Screen Shot 2021-12-21 at 19 43 15](https://user-images.githubusercontent.com/6406986/146975107-dcb939eb-6675-4e10-a6fa-a9edefaefcdd.png)

**Comment by corinnewo** [comment] 2021-12-22 14:51
@dakom In ideation - see #2076
If it is a matter of making the legacy game slightly smaller and placed above the bar, is that you or Mendy?

**Comment by dakom** [comment] 2021-12-22 15:02
Having the clickable interactive menu on top of a clickable interactive screen which can display all sorts of unpredictable content is **fundamentally flawed**. Even with a grid and warning to users.

What if we ported something like `Make it Grow`? The controlbar would go right on top of the tools they are supposed to click and/or look very bad right next to them.

What if the user wants the entire screen to be the video? We are telling them they can't, they _must_ have a big empty gap at the bottom?

What if we port "catch the fruit" - the avatar has to float above some distance?

This is really inevitable, there is going to come a time where the controlbar (and settings buttons) are going to need to move outside of the screen. Might as well solve that now.

**Comment by dakom** [comment] 2021-12-22 15:03
In any case, yes, placing the containing frame for the module is something that happens on the jig player level, not within a module, so it's @MendyBerger

**Comment by corinnewo** [comment] 2021-12-22 15:06
@GaliShapira please see David's comments above.

**Comment by GaliShapira** [comment] 2021-12-22 17:47
There was a UX+Development decision to change the player format to 16x9. 
There was a UX decision to show the game expanded full size.
Therefore a lot of work was done:

- [Panels were designed floating ](https://zpl.io/2E83eKe)
- Huge collection of backgrounds and overlays made so that important content is not covered by the panels
- [A  grid was designed for the creator to alert him from placing content outside of the frame.
](https://zpl.io/a7P8x4K)
We now have a problem with the legacy games, we need to place them smaller within the frame that was defined. 

Users will see video as all other screens in the size of the defined frame its quite big, so they are still in the platform steps and can click on next or mute etc. 
Content will not be placed under the panels.

We need to add the panels to the preview mode, and we need to add the grid+frame+notification as designed.

**Comment by dakom** [comment] 2021-12-22 18:40
The intent of Jigzi was that it be modular enough to support *anything* that can exist in a HTML frame. That's the entire point - we structured it so that modules can exist independent of eachother. Right now this is what allows having memory game and drag and drop, but it can also allow platformer games, 3d scenes, music creation, and all sorts of content.

Covering up the screen with a controlbar is a *huge* mistake imho. If Jigzi thrives, by definition this will be overrulled later. It can't be any other way. For example, you can't have a module which is like Super Mario right now. You can't have anything like Minecraft either. 

We can all come up with a dozen examples where the user is going to want to see what's happening in the bottom row of the screen.

Not all modules will be Tiny Tap clones (or at least, I hope so!!!)

This issue has nothing at all to do with the legacy player or 16:9 vs. 4:3. It has to do with getting the UI elements off the module screen so that modules are free to do anything the Ji team (or open-source contributors) can imagine.

**Comment by GaliShapira** [comment] 2021-12-22 18:55
I dont see these kinds of activities or atmosphere as our goal for this stage.
If Chana wants to open this discussion at this stage I dont object.

**Comment by dakom** [comment] 2021-12-22 20:41
We had lots of discussions early on about what "Ji 2.0" meant, how it would be different from Tiny Tap, and what the long-term vision of the platform looked like. We had specific discussions about WebGL and even talked a bit about resurrecting some of our old content (specifically "fruit catching" from Ji Calendar, in a way that teachers could skin it for letters or other learning images). We had even tossed around some early ideas for 3d stuff and whether we could embed Unity projects.

The decision was crystal clear: we were going to build a platform that would allow for those different kinds of activities, but we weren't going to add those activities in phase 1. "Just" the infrastructure to support it.

That has (huge, gigantic) implications on the tech level, and design needs to support that vision too.

If all we needed to do was build a glorified Tiny Tap clone, we could have saved a solid 8 months, at least.

By way of analogy, the entire Tiny Tap player is *just one module*.

Jigzi is supposed to be far more powerful than this imho.

This really needs to be brought up more in Ideation because it sounds to me like the message has gotten lost.

**Comment by GaliShapira** [comment] 2021-12-23 07:49
I hear you David.
I'm just not sure that now is the time to reopen this issue. 
If Chana, Corinne feel like opening it, lets have a meeting and discuss.

**Comment by MendyBerger** [comment] 2021-12-28 21:28
Resolved in 964be48c0222334a4676eecb309e62ecaf08ae2b

Will only be visible once the legacy games are uploaded without covers

**Closed by MendyBerger** 2021-12-28 21:28 UTC
Labels: legacy
